# Generated by Django 3.1.4 on 2021-01-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('CourseNum', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('Title', models.CharField(default='', max_length=60)),
                ('Instructor', models.CharField(default='', max_length=60)),
                ('Duration', models.FloatField()),
            ],
        ),
    ]
